version = 0.1
[default.deploy.parameters]
stack_name = "mini-tools-stack"
resolve_s3 = true
s3_prefix = "mini-tools-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
